project:
  type: website
  output-dir: docs 
  render:
    - slides/01_intro.qmd
    - slides/02_graphs.qmd
    - slides/03_exper.qmd
    - slides/04_ob_conf.qmd
    - slides/05_dml.qmd
    - slides/06_hte.qmd
    - slides/07_unob_conf.qmd
    - slides/08_did.qmd
execute:
  freeze: false  # re-render only when source changes
  
format-resources:
  - assets/author_pic.jpg
  - assets/tie_code.theme
  
format:
  revealjs: 
    highlight-style: assets/tie_code.theme